### ISSUE TITLE
A* search with manhattan distance as Heuristic.

### ISSUE THREAD

**Issue by Davidmenamm** [shaniadicen/eight-puzzle-search#2]
I was testing the program and possibly found an issue, when calculating the A* search with the manhattan distance as heuristic.

**Comment by shaniadicen** [comment]
Hi! I believe I never finished this program during university but feel free to do a pull request for a solution to the issue you found if that is something that interests you. Thanks!

**Comment by Davidmenamm** [comment]
No, it's fine for now, just wondering. Although to highlight, the error that I identified, was in the class aStarSearch in the method solve puzzle.

**Comment by shaniadicen** [comment]
I'll probably never get the time to fix this but thanks for catching that!
